sudo: false

language: Python
python:
  - "2.7"

install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION pandas numpy
  - source activate test-environment
  - conda install --file conda-requirements.txt # xlrd, possibly others
  - export BUILD_DIR=`pwd`
  - pip install -r requirements.txt
  #- conda install -c ospc taxcalc
  - git clone https://github.com/jdebacker/Tax-Calculator.git && cd Tax-Calculator
  - git fetch --all && git checkout master && python setup.py install && cd $BUILD_DIR
  - export BTAX_OUT_DIR=btax_output_dir # make an output dir
  - export BTAX_CUR_DIR=${BUILD_DIR}/btax
  - mkdir btax_output_dir
  - python setup.py develop

script:
  - py.test -m "not slow and not needs_puf" ${BTAX_CUR_DIR}/tests

